#ifndef BLOCKS_H_
#define BLOCKS_H_

typedef enum {

    CONF_BLOCK_PROGRAM,
    CONF_BLOCK_USER_SCALE,
    CONF_BLOCK_PAD_CALIBRATION,
    CONF_BLOCK_MIDI,
    CONF_BLOCK_PRESSURE_SETTINGS,
    CONF_BLOCKS

} blocks;

#endif