#pragma once

#include "../../interface/pads/curves/Curves.h"

#define NUMBER_OF_PROGRAMS                          20
#define DEFAULT_ACTIVE_PROGRAM                      0
#define DEFAULT_ACTIVE_SCALE                        0

typedef enum
{
    programLastActiveProgramSection,
    programLastActiveScaleSection,
    programGlobalSettingsSection,
    programLocalSettingsSection,
    PROGRAM_SECTIONS
} programSections;

//define default global program settings
#define GLOBAL_PROGRAM_SETTING_SPLIT_STATE          0x00
#define GLOBAL_PROGRAM_SETTING_X_ENABLE             0x01
#define GLOBAL_PROGRAM_SETTING_Y_ENABLE             0x01
#define GLOBAL_PROGRAM_SETTING_NOTE_ENABLE          0x01
#define GLOBAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE    0x01
#define GLOBAL_PROGRAM_SETTING_MIDI_CHANNEL         0x01
#define GLOBAL_PROGRAM_SETTING_CC_X                 0x14
#define GLOBAL_PROGRAM_SETTING_CC_Y                 0x15
#define GLOBAL_PROGRAM_SETTING_X_MIN                0
#define GLOBAL_PROGRAM_SETTING_X_MAX                127
#define GLOBAL_PROGRAM_SETTING_Y_MIN                0
#define GLOBAL_PROGRAM_SETTING_Y_MAX                127
#define GLOBAL_PROGRAM_SETTING_X_CURVE_GAIN         curve_linear_up
#define GLOBAL_PROGRAM_SETTING_Y_CURVE_GAIN         curve_linear_up

typedef enum
{
    //list of IDs for global program settings for access
    GLOBAL_PROGRAM_SETTING_SPLIT_STATE_ID,
    GLOBAL_PROGRAM_SETTING_X_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_Y_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_NOTE_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_MIDI_CHANNEL_ID,
    GLOBAL_PROGRAM_SETTING_CC_X_ID,
    GLOBAL_PROGRAM_SETTING_CC_Y_ID,
    GLOBAL_PROGRAM_SETTING_X_MIN_ID,
    GLOBAL_PROGRAM_SETTING_X_MAX_ID,
    GLOBAL_PROGRAM_SETTING_Y_MIN_ID,
    GLOBAL_PROGRAM_SETTING_Y_MAX_ID,
    GLOBAL_PROGRAM_SETTING_X_CURVE_GAIN_ID,
    GLOBAL_PROGRAM_SETTING_Y_CURVE_GAIN_ID,
    GLOBAL_PROGRAM_SETTINGS
} globalProgramSettings;

//put global settings in array for easier access
const uint8_t defaultGlobalProgramSettingArray[GLOBAL_PROGRAM_SETTINGS] =
{
    GLOBAL_PROGRAM_SETTING_SPLIT_STATE,
    GLOBAL_PROGRAM_SETTING_X_ENABLE,
    GLOBAL_PROGRAM_SETTING_Y_ENABLE,
    GLOBAL_PROGRAM_SETTING_NOTE_ENABLE,
    GLOBAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE,
    GLOBAL_PROGRAM_SETTING_MIDI_CHANNEL,
    GLOBAL_PROGRAM_SETTING_CC_X,
    GLOBAL_PROGRAM_SETTING_CC_Y,
    GLOBAL_PROGRAM_SETTING_X_MIN,
    GLOBAL_PROGRAM_SETTING_X_MAX,
    GLOBAL_PROGRAM_SETTING_Y_MIN,
    GLOBAL_PROGRAM_SETTING_Y_MAX,
    GLOBAL_PROGRAM_SETTING_X_CURVE_GAIN,
    GLOBAL_PROGRAM_SETTING_Y_CURVE_GAIN
};

#define LOCAL_PROGRAM_SETTING_X_ENABLE              0x01
#define LOCAL_PROGRAM_SETTING_Y_ENABLE              0x01
#define LOCAL_PROGRAM_SETTING_NOTE_ENABLE           0x01
#define LOCAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE     0x01
#define LOCAL_PROGRAM_SETTING_MIDI_CHANNEL          0x01
#define LOCAL_PROGRAM_SETTING_CC_X                  0x14
#define LOCAL_PROGRAM_SETTING_CC_Y                  0x15
#define LOCAL_PROGRAM_SETTING_X_MIN                 0
#define LOCAL_PROGRAM_SETTING_X_MAX                 127
#define LOCAL_PROGRAM_SETTING_Y_MIN                 0
#define LOCAL_PROGRAM_SETTING_Y_MAX                 127
#define LOCAL_PROGRAM_SETTING_X_CURVE_GAIN          curve_linear_up
#define LOCAL_PROGRAM_SETTING_Y_CURVE_GAIN          curve_linear_up

typedef enum
{
    LOCAL_PROGRAM_SETTING_X_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_Y_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_NOTE_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_MIDI_CHANNEL_ID,
    LOCAL_PROGRAM_SETTING_CC_X_ID,
    LOCAL_PROGRAM_SETTING_CC_Y_ID,
    LOCAL_PROGRAM_SETTING_X_MIN_ID,
    LOCAL_PROGRAM_SETTING_X_MAX_ID,
    LOCAL_PROGRAM_SETTING_Y_MIN_ID,
    LOCAL_PROGRAM_SETTING_Y_MAX_ID,
    LOCAL_PROGRAM_SETTING_X_CURVE_GAIN_ID,
    LOCAL_PROGRAM_SETTING_Y_CURVE_GAIN_ID,
    LOCAL_PROGRAM_SETTINGS
} localProgramSettings;

const uint8_t defaultLocalProgramSettingArray[] =
{
    LOCAL_PROGRAM_SETTING_X_ENABLE,
    LOCAL_PROGRAM_SETTING_Y_ENABLE,
    LOCAL_PROGRAM_SETTING_NOTE_ENABLE,
    LOCAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE,
    LOCAL_PROGRAM_SETTING_MIDI_CHANNEL,
    LOCAL_PROGRAM_SETTING_CC_X,
    LOCAL_PROGRAM_SETTING_CC_Y,
    LOCAL_PROGRAM_SETTING_X_MIN,
    LOCAL_PROGRAM_SETTING_X_MAX,
    LOCAL_PROGRAM_SETTING_Y_MIN,
    LOCAL_PROGRAM_SETTING_Y_MAX,
    LOCAL_PROGRAM_SETTING_X_CURVE_GAIN,
    LOCAL_PROGRAM_SETTING_Y_CURVE_GAIN
};
