#ifdef BOARD_R2
#include "../Board.h"

void Board::initPins()
{
    //leds
    setOutput(LED_ROW_1_PORT, LED_ROW_1_PIN);
    setOutput(LED_ROW_2_PORT, LED_ROW_2_PIN);
    setOutput(LED_ROW_3_PORT, LED_ROW_3_PIN);

    #ifdef LED_INVERT
    setHigh(LED_ROW_1_PORT, LED_ROW_1_PIN);
    setHigh(LED_ROW_2_PORT, LED_ROW_2_PIN);
    setHigh(LED_ROW_3_PORT, LED_ROW_3_PIN);
    #else
    setLow(LED_ROW_1_PORT, LED_ROW_1_PIN);
    setLow(LED_ROW_2_PORT, LED_ROW_2_PIN);
    setLow(LED_ROW_3_PORT, LED_ROW_3_PIN);
    #endif

    setOutput(DECODER_OUT_1_PORT, DECODER_OUT_1_PIN);
    setOutput(DECODER_OUT_2_PORT, DECODER_OUT_2_PIN);
    setOutput(DECODER_OUT_3_PORT, DECODER_OUT_3_PIN);

    setLow(DECODER_OUT_1_PORT, DECODER_OUT_1_PIN);
    setLow(DECODER_OUT_2_PORT, DECODER_OUT_2_PIN);
    setLow(DECODER_OUT_3_PORT, DECODER_OUT_3_PIN);

    //pads
    setOutput(MUX_COMMON_PIN_0_PORT, MUX_COMMON_PIN_0_PIN);
    setOutput(MUX_COMMON_PIN_1_PORT, MUX_COMMON_PIN_1_PIN);
    setOutput(MUX_COMMON_PIN_2_PORT, MUX_COMMON_PIN_2_PIN);
    setOutput(MUX_COMMON_PIN_3_PORT, MUX_COMMON_PIN_3_PIN);

    setOutput(MUX_SELECT_PIN_0_PORT, MUX_SELECT_PIN_0_PIN);
    setOutput(MUX_SELECT_PIN_1_PORT, MUX_SELECT_PIN_1_PIN);
    setOutput(MUX_SELECT_PIN_2_PORT, MUX_SELECT_PIN_2_PIN);
    setOutput(MUX_SELECT_PIN_3_PORT, MUX_SELECT_PIN_3_PIN);

    setLow(MUX_SELECT_PIN_0_PORT, MUX_SELECT_PIN_0_PIN);
    setLow(MUX_SELECT_PIN_1_PORT, MUX_SELECT_PIN_1_PIN);
    setLow(MUX_SELECT_PIN_2_PORT, MUX_SELECT_PIN_2_PIN);
    setLow(MUX_SELECT_PIN_3_PORT, MUX_SELECT_PIN_3_PIN);

    setHigh(MUX_COMMON_PIN_0_PORT, MUX_COMMON_PIN_0_PIN);
    setHigh(MUX_COMMON_PIN_1_PORT, MUX_COMMON_PIN_1_PIN);
    setHigh(MUX_COMMON_PIN_2_PORT, MUX_COMMON_PIN_2_PIN);
    setHigh(MUX_COMMON_PIN_3_PORT, MUX_COMMON_PIN_3_PIN);

    //input shift register
    setInput(INPUT_SHIFT_REG_IN_PORT, INPUT_SHIFT_REG_IN_PIN);
    setOutput(INPUT_SHIFT_REG_LATCH_PORT, INPUT_SHIFT_REG_LATCH_PIN);
    setOutput(INPUT_SHIFT_REG_CLOCK_PORT, INPUT_SHIFT_REG_CLOCK_PIN);

    //input matrix decoder
    setOutput(DECODER_IN_A0_PORT, DECODER_IN_A0_PIN);
    setOutput(DECODER_IN_A1_PORT, DECODER_IN_A1_PIN);
    setOutput(DECODER_IN_A2_PORT, DECODER_IN_A2_PIN);
}
#endif