#pragma once

//typedefs used to correctly retrieve/update parameter from database
//a typedef element marks location inside database block/section

typedef enum
{
    //list of IDs for global program settings for access
    GLOBAL_PROGRAM_SETTING_SPLIT_STATE_ID,
    GLOBAL_PROGRAM_SETTING_X_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_Y_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_NOTE_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE_ID,
    GLOBAL_PROGRAM_SETTING_MIDI_CHANNEL_ID,
    GLOBAL_PROGRAM_SETTING_CC_X_ID,
    GLOBAL_PROGRAM_SETTING_CC_Y_ID,
    GLOBAL_PROGRAM_SETTING_X_MIN_ID,
    GLOBAL_PROGRAM_SETTING_X_MAX_ID,
    GLOBAL_PROGRAM_SETTING_Y_MIN_ID,
    GLOBAL_PROGRAM_SETTING_Y_MAX_ID,
    GLOBAL_PROGRAM_SETTING_X_CURVE_GAIN_ID,
    GLOBAL_PROGRAM_SETTING_Y_CURVE_GAIN_ID,
    GLOBAL_PROGRAM_SETTINGS
} globalProgramSettings;

typedef enum
{
    LOCAL_PROGRAM_SETTING_X_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_Y_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_NOTE_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_AFTERTOUCH_ENABLE_ID,
    LOCAL_PROGRAM_SETTING_MIDI_CHANNEL_ID,
    LOCAL_PROGRAM_SETTING_CC_X_ID,
    LOCAL_PROGRAM_SETTING_CC_Y_ID,
    LOCAL_PROGRAM_SETTING_X_MIN_ID,
    LOCAL_PROGRAM_SETTING_X_MAX_ID,
    LOCAL_PROGRAM_SETTING_Y_MIN_ID,
    LOCAL_PROGRAM_SETTING_Y_MAX_ID,
    LOCAL_PROGRAM_SETTING_X_CURVE_GAIN_ID,
    LOCAL_PROGRAM_SETTING_Y_CURVE_GAIN_ID,
    LOCAL_PROGRAM_SETTINGS
} localProgramSettings;

typedef enum
{
    MIDI_SETTING_AFTERTOUCH_TYPE_ID,
    MIDI_SETTING_RUNNING_STATUS_ID,
    MIDI_SETTING_NOTE_OFF_TYPE_ID,
    MIDI_SETTING_TRANSPORT_CC_ID,
    MIDI_SETTING_TRANSPORT_CC_PLAY_ID,
    MIDI_SETTING_TRANSPORT_CC_STOP_ID,
    MIDI_SETTING_TRANSPORT_CC_RECORD_ID,
    MIDI_SETTINGS
} midiSettings;

typedef enum
{
    PRESSURE_SETTING_SENSITIVITY_ID,
    PRESSURE_SETTING_CURVE_ID,
    PRESSURE_SETTINGS
} pressureSettings;

typedef enum
{
    PREDEFINED_SCALE_OCTAVE_ID,
    PREDEFINED_SCALE_TONIC_ID,
    PREDEFINED_SCALE_SHIFT_ID,
    PREDEFINED_SCALE_PARAMETERS
} predefinedScaleParameters;
